// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD46pacJAau6aYZxDpcKnGjCrdveeIgQok',
    appId: '1:424779749983:android:eb09ea3e4e604a73d399ea',
    messagingSenderId: '424779749983',
    projectId: 'sep490-fa25se182',
    storageBucket: 'sep490-fa25se182.firebasestorage.app',
  );

  static String toHttpsUrl(String gsUrl) {
    if (!gsUrl.startsWith('gs://')) {
      return gsUrl;
    }
    const String bucket = 'sep490-fa25se182.firebasestorage.app';
    final uri = Uri.parse(gsUrl);

    final pathSegments = uri.pathSegments;
    if (pathSegments.isEmpty) return gsUrl;

    final path = pathSegments.sublist(1).join('/');
    final encodedPath = path.split('/').map(Uri.encodeComponent).join('/');

    const String token = '94bb30d6-b65e-457f-bb07-e2b4740ee925';

    return 'https://firebasestorage.googleapis.com/v0/b/$bucket/o/audios%2F$encodedPath?alt=media&token=$token';
  }

}